apiVersion: v1
kind: Service
metadata:
  name: mira-news-backend
  namespace: mira-news
spec:
  selector:
    app: mira-news-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
