apiVersion: v1
kind: Service
metadata:
  name: mira-news-frontend
  namespace: mira-news
spec:
  selector:
    app: mira-news-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
